networks:
  proxy:
    external: true

services:
  www:
    build: .
    hostname: www
    container_name: www
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      - redis
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
      - PATH=/rails/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - rails-storage:/app/storage

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "6379:6379"

volumes:
  rails-storage: