networks:
  proxy:
    external: true

services:
  www:
    build: .
    hostname: www
    container_name: www
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
