
services:
  www:
    build: .
    hostname: www
    container_name: www
    restart: unless-stopped
    environment:
      - RAILS_MASTER_KEY=EyOUjGCoUxGm9SKE
      - MESSAGE_ENCRYPTION_KEY=EyOUjGCoUxGm9SKE
