
services:
  www:
    build: .
    hostname: www
    container_name: www
    restart: unless-stopped
    environment:
      - RAILS_MASTER_KEY=rrD2Asoa7iZZsrcm+ULAezsTjdrNFlutO0xFaE1B2bIUkCycSDiv+UC6Fw13cGoGgCc8ONoIMEdYKt9javw7D4v91q6XovUr99u6JrJEzHSgDZBh0r4QHjHA93qdhe/JaScHRb8wf4UorvFheXhYWfwqPWzAol/GzpB0KFHunCgZUW6XBzxPNURUu6Dqa+WEnmfwrlOyHi3KkaJYB5Amf0593AsYNynH/cA715ajPtfVd2Wi8327qzVeV7QcjrB4ZYQoiAHRbP+UXCV8Mo6esXZ6uxTTYQVsIz9Q0vvWI9dnrYXweL2+3KvWuAK2RS1Ur/BDnq40vOFudsFmwt6V/spYuYPo2gB8vGKRfZLTc8q/9EMEn+eDlke7SfjnbN4MCauoqaCgnS6bGyiBdBjClPBEkcim--cTFyOgd5A009j0Pb--CeNAixP+QV6o7d0bh93aMQ==%
