default: &default
    encoding: unicode
    pool: 5

development:
    <<: *default
    adapter: sqlite3
    timeout: 5000
    database: db/development.sqlite3

production:
    <<: *default
    adapter: postgresql
    database: web
    host: postgres
    username: web
    password: 621Se2pl

